### ISSUE TITLE
Swindler does not compile on Xcode 10.2

### ISSUE THREAD

**Issue by thieso2** [tmandry/Swindler#57]
The new compiler seems more picky. I would try to fix it myself and my Swift Kung-Fu is not yet strong enough to see the fixes immediately. I tried setting the SWIFT_VERSION to 4.x, it does not help. Once you have upgraded to Xcode 10.2 you cannot compile Swindler any more.

 I have attached the output of:

```xcodebuild -workspace "Swindler.xcworkspace" -scheme "Swindler" | xcpretty```

Mostly it complains about "parameter ... could not be inferred".

[xcodebuild-xcpretty.log](https://github.com/tmandry/Swindler/files/3007667/xcodebuild-xcpretty.log)

**Comment by wizardguy** [comment]
Same issue.

**Comment by tmandry** [comment]
This looks like it will take some time to get to the bottom of. The way Swift type constraints / inference has worked since the beginning of the project just changed in a minor version of Xcode.

I'll need to set aside some time to minimize the error down to a smaller example so I can play with it and understand what's going on. If anyone is interested in doing this minimization, feel free, otherwise I'll get to it when I can set aside a few hours to work on this.
